### ISSUE TITLE
File "monitor.py", line 295 with open(pidfile, "w") as file_handle:

### ISSUE THREAD

**Issue by kovalroma** [jamesoff/simplemonitor#37]
Hello!

I am trying to launch this script on my CentOS. 
I've got error:

 File "monitor.py", line 295
    with open(pidfile, "w") as file_handle:
            ^
SyntaxError: invalid syntax

**Comment by jamesoff** [comment]
What version of Python do you have?

**Comment by kovalroma** [comment]
Python 2.4.3

**Comment by jamesoff** [comment]
That'll do it, 2.4 doesn't understand the `with` syntax :(

Can you upgrade Python? SimpleMonitor works on 2.6, if you can reach that.

**Comment by kovalroma** [comment]
Hm, I will try to update. 
Thank you!

**Comment by kovalroma** [comment]
New error report on Python 2.7.12

 python2.7 monitor.py 
Traceback (most recent call last):
  File "monitor.py", line 16, in <module>
    import Monitors.network
  File "/opt/monitoring/Monitors/network.py", line 18, in <module>
    class HTTPSClientAuthHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'

**Comment by jamesoff** [comment]
Looks like that's caused by Python not having SSL, I'll put in a fix.

**Comment by jamesoff** [comment]
@kovalroma are you able to test the bugfix/ssl branch to see if it works for you?

**Comment by kovalroma** [comment]
@jamesoff  yes, I've checked. 

It works OK from bugfix/ssl branch. 

Thank you.
